import 'package:records/database/records.dart';

class RecordsData {
  List<Records> records = [
    Records(
        name: 'Taksh Panchal',
        phoneNumber: '9876543210',
        city: 'Mumbai',
        imageUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
        rupees: 45),
    Records(
        name: 'Priya Sharma',
        phoneNumber: '9876543211',
        city: 'Delhi',
        imageUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
        rupees: 78),
    Records(
        name: 'Vihaan Shah',
        phoneNumber: '9876543212',
        city: 'Bangalore',
        imageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
        rupees: 92),
    Records(
        name: 'Ananya Desai',
        phoneNumber: '9876543213',
        city: 'Pune',
        imageUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
        rupees: 33),
    Records(
        name: 'Arjun Mehta',
        phoneNumber: '9876543214',
        city: 'Ahmedabad',
        imageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
        rupees: 67),
    Records(
        name: 'Zara Modi',
        phoneNumber: '9876543215',
        city: 'Chennai',
        imageUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
        rupees: 89),
    Records(
        name: 'Reyansh Joshi',
        phoneNumber: '9876543216',
        city: 'Kolkata',
        imageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
        rupees: 23),
    Records(
        name: 'Myra Gandhi',
        phoneNumber: '9876543217',
        city: 'Hyderabad',
        imageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
        rupees: 56),
    Records(
        name: 'Kabir Soni',
        phoneNumber: '9876543218',
        city: 'Jaipur',
        imageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
        rupees: 72),
    Records(
        name: 'Aanya Trivedi',
        phoneNumber: '9876543219',
        city: 'Lucknow',
        imageUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
        rupees: 44),
    Records(
        name: 'Vivaan Bhatt',
        phoneNumber: '9876543220',
        city: 'Chandigarh',
        imageUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
        rupees: 88),
    Records(
        name: 'Ishani Sharma',
        phoneNumber: '9876543221',
        city: 'Indore',
        imageUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
        rupees: 31),
    Records(
        name: 'Aarav Rana',
        phoneNumber: '9876543222',
        city: 'Bhopal',
        imageUrl: 'https://randomuser.me/api/portraits/men/13.jpg',
        rupees: 95),
    Records(
        name: 'Prisha Dave',
        phoneNumber: '9876543223',
        city: 'Surat',
        imageUrl: 'https://randomuser.me/api/portraits/women/14.jpg',
        rupees: 27),
    Records(
        name: 'Dhruv Parikh',
        phoneNumber: '9876543224',
        city: 'Vadodara',
        imageUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
        rupees: 63),
    Records(
        name: 'Avni Thakkar',
        phoneNumber: '9876543225',
        city: 'Nagpur',
        imageUrl: 'https://randomuser.me/api/portraits/women/16.jpg',
        rupees: 82),
    Records(
        name: 'Ved Chauhan',
        phoneNumber: '9876543226',
        city: 'Thane',
        imageUrl: 'https://randomuser.me/api/portraits/men/17.jpg',
        rupees: 41),
    Records(
        name: 'Anvi Raval',
        phoneNumber: '9876543227',
        city: 'Nashik',
        imageUrl: 'https://randomuser.me/api/portraits/women/18.jpg',
        rupees: 76),
    Records(
        name: 'Shaurya Vyas',
        phoneNumber: '9876543228',
        city: 'Faridabad',
        imageUrl: 'https://randomuser.me/api/portraits/men/19.jpg',
        rupees: 54),
    Records(
        name: 'Kiara Jani',
        phoneNumber: '9876543229',
        city: 'Gurgaon',
        imageUrl: 'https://randomuser.me/api/portraits/women/20.jpg',
        rupees: 93),
    Records(
        name: 'Advait Sheth',
        phoneNumber: '9876543230',
        city: 'Noida',
        imageUrl: 'https://randomuser.me/api/portraits/men/21.jpg',
        rupees: 38),
    Records(
        name: 'Aisha Vora',
        phoneNumber: '9876543231',
        city: 'Ghaziabad',
        imageUrl: 'https://randomuser.me/api/portraits/women/22.jpg',
        rupees: 87),
    Records(
        name: 'Pranav Dalal',
        phoneNumber: '9876543232',
        city: 'Rajkot',
        imageUrl: 'https://randomuser.me/api/portraits/men/23.jpg',
        rupees: 29),
    Records(
        name: 'Sara Zaveri',
        phoneNumber: '9876543233',
        city: 'Amritsar',
        imageUrl: 'https://randomuser.me/api/portraits/women/24.jpg',
        rupees: 69),
    Records(
        name: 'Aryan Bhagat',
        phoneNumber: '9876543234',
        city: 'Allahabad',
        imageUrl: 'https://randomuser.me/api/portraits/men/25.jpg',
        rupees: 51),
    Records(
        name: 'Mira Doshi',
        phoneNumber: '9876543235',
        city: 'Ranchi',
        imageUrl: 'https://randomuser.me/api/portraits/women/26.jpg',
        rupees: 94),
    Records(
        name: 'Ishaan Kapadia',
        phoneNumber: '9876543236',
        city: 'Coimbatore',
        imageUrl: 'https://randomuser.me/api/portraits/men/27.jpg',
        rupees: 42),
    Records(
        name: 'Riya Chokshi',
        phoneNumber: '9876543237',
        city: 'Visakhapatnam',
        imageUrl: 'https://randomuser.me/api/portraits/women/28.jpg',
        rupees: 77),
    Records(
        name: 'Aadi Mehta',
        phoneNumber: '9876543238',
        city: 'Kochi',
        imageUrl: 'https://randomuser.me/api/portraits/men/29.jpg',
        rupees: 35),
    Records(
        name: 'Saanvi Raja',
        phoneNumber: '9876543239',
        city: 'Trivandrum',
        imageUrl: 'https://randomuser.me/api/portraits/women/30.jpg',
        rupees: 83),
    Records(
        name: 'Veer Contractor',
        phoneNumber: '9876543240',
        city: 'Madurai',
        imageUrl: 'https://randomuser.me/api/portraits/men/31.jpg',
        rupees: 48),
    Records(
        name: 'Anika Shroff',
        phoneNumber: '9876543241',
        city: 'Mysore',
        imageUrl: 'https://randomuser.me/api/portraits/women/32.jpg',
        rupees: 91),
    Records(
        name: 'Reyansh Sanghvi',
        phoneNumber: '9876543242',
        city: 'Guwahati',
        imageUrl: 'https://randomuser.me/api/portraits/men/33.jpg',
        rupees: 25),
    Records(
        name: 'Kyra Parekh',
        phoneNumber: '9876543243',
        city: 'Dehradun',
        imageUrl: 'https://randomuser.me/api/portraits/women/34.jpg',
        rupees: 73),
    Records(
        name: 'Armaan Desai',
        phoneNumber: '9876543244',
        city: 'Varanasi',
        imageUrl: 'https://randomuser.me/api/portraits/men/35.jpg',
        rupees: 59),
    Records(
        name: 'Aadhya Vakil',
        phoneNumber: '9876543245',
        city: 'Patna',
        imageUrl: 'https://randomuser.me/api/portraits/women/36.jpg',
        rupees: 86),
    Records(
        name: 'Neil Majmudar',
        phoneNumber: '9876543246',
        city: 'Raipur',
        imageUrl: 'https://randomuser.me/api/portraits/men/37.jpg',
        rupees: 32),
    Records(
        name: 'Mishka Gandhi',
        phoneNumber: '9876543247',
        city: 'Shimla',
        imageUrl: 'https://randomuser.me/api/portraits/women/38.jpg',
        rupees: 97),
    Records(
        name: 'Ayaan Mehta',
        phoneNumber: '9876543248',
        city: 'Mangalore',
        imageUrl: 'https://randomuser.me/api/portraits/men/39.jpg',
        rupees: 45),
    Records(
        name: 'Shanaya Iyer',
        phoneNumber: '9876543249',
        city: 'Thiruvananthapuram',
        imageUrl: 'https://randomuser.me/api/portraits/women/40.jpg',
        rupees: 68),
    Records(
        name: 'Kabir Thakker',
        phoneNumber: '9876543250',
        city: 'Bhubaneswar',
        imageUrl: 'https://randomuser.me/api/portraits/men/41.jpg',
        rupees: 53),
    Records(
        name: 'Zara Mehta',
        phoneNumber: '9876543251',
        city: 'Gandhinagar',
        imageUrl: 'https://randomuser.me/api/portraits/women/42.jpg',
        rupees: 79),
    Records(
        name: 'Vihaan Parekh',
        phoneNumber: '9876543252',
        city: 'Vijaywada',
        imageUrl: 'https://randomuser.me/api/portraits/men/43.jpg',
        rupees: 37),
  ];
}
